### ISSUE TITLE
Update Geocoding request URL for Google

### ISSUE THREAD

**Issue by dominikasbgw** [gregorwolf/zgeocode#1]
Hi Gregor,

Please update the Geocoding request URL generator for Google.
We're having some issues with the Geocoding results.
In order to fix this I have checked Google's documentation.
There's an filter option for postal code and country.
See [https://developers.google.com/maps/documentation/geocoding/requests-geocoding#component-filtering](https://developers.google.com/maps/documentation/geocoding/requests-geocoding#component-filtering)

So please add this filter option to the URL generator in method "GEOCODE_ONE_ADDRESS".

I also found that you can use commas as a separator in the URL.
See [https://developers.google.com/maps/documentation/geocoding/start#geocoding-request-and-response-latitudelongitude-lookup](https://developers.google.com/maps/documentation/geocoding/start#geocoding-request-and-response-latitudelongitude-lookup)
So please also add commas  and spaces to the separator.

FYI:
I have modified "GEOCODE_ONE_ADDRESS" in our system like this:
`lv_path = add_part( iv_url = lv_path iv_param = address-address-street && | | && address-address-house_num1 iv_sep = 'address=' ).`
`lv_path = add_part( iv_url = lv_path iv_param = address-address-post_code1 iv_sep = ',%20' ).`
`lv_path = add_part( iv_url = lv_path iv_param = ' ' && | | && address-address-city1      iv_sep = ' ').`
`lv_path = add_part( iv_url = lv_path iv_param = country    iv_sep = ',%20' )`
`lv_path = add_part( iv_url = lv_path iv_param = address-address-post_code1 iv_sep = '&components=postal_code:' ).`
`lv_path = lv_path && '|country:' && address-address-country.`

Best regards
Dominik

**Comment by gregorwolf** [comment]
Hi Dominik,

thank you for the heads up. Would it be possible to provide your improvement via a pull request?

Thank you in advance.

Best Regards
Gregor

**Comment by dominikasbgw** [comment]
Hi Gregor,

Thanks for your reply.
Yes, I can do that.
Please see pull request #2 .

Best regards
Dominik
